name: Artifact Expiry Demo

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create data
        run: echo "Artifact created at $(date)" > artifact.txt

      - uses: actions/upload-artifact@v4
        with:
          name: test_artifact
          path: artifact.txt
          retention-days: 1

  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test_artifact

      - name: Display artifact data
        run: cat artifact.txt

      - name: Fail so just this job can be rerun.
        run: false
